name: Daily Report

on:
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

env:
  EMAIL_USER_EMAIL: ${{ secrets.EMAIL_USER_EMAIL }}
  EMAIL_USER_PASS: ${{ secrets.EMAIL_USER_PASS }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}

jobs:
  report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    
    - run: node ./src/main.js
