name: Daily Report

on:
  schedule:
  - cron: "0 14 * * *"
  workflow_dispatch:

env:
  EMAIL_USER_EMAIL: ${{ secrets.EMAIL_USER_EMAIL }}
  EMAIL_USER_PASS: ${{ secrets.EMAIL_USER_PASS }}
  EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}

jobs:
  report:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: npm ci
    - run: node src/main.js
